ServerIP: "0.0.0.0:8080"
DBConn: user=sol password= host= port=5432 dbname=
LogfileOn: false
Logfile: "/home/sol/ping-api-server/ping-api.log.dev"
Clusters:
 - MainnetBeta
 - Testnet
 - Devnet
SolanaConfig:
  Dir: "/home/sol/.config/solana/cli/"
  Mainnet: "config-mainnet-beta.yml"
  Testnet: "config-testnet.yml"
  Devnet: "config-devnet.yml"
SolanaPing:
 PingExePath: "/home/sol/.local/share/solana/install/active_release/bin"
 Count: 3
 Inverval: 1
 Timeout: 300
 PerPingTime: 30
Slack:
 WebHook: 
 ReportTime: 300
 Clusters:
  - MainnetBeta
  - Testnet
  - Devnet




